//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public Alumno()
        {
            this.MateriaAlumno = new HashSet<MateriaAlumno>();
        }
    
        public int matricula { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public int semestre { get; set; }
        public int facultad { get; set; }
        public int ciudad { get; set; }
    
        public virtual Ciudad Ciudad1 { get; set; }
        public virtual Facultad Facultad1 { get; set; }
        public virtual ICollection<MateriaAlumno> MateriaAlumno { get; set; }
    }
}
