//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facultad
    {
        public Facultad()
        {
            this.Alumno = new HashSet<Alumno>();
            this.MateriaFacultad = new HashSet<MateriaFacultad>();
        }
    
        public int ID_Facultad { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int universidad { get; set; }
        public int ciudad { get; set; }
    
        public virtual ICollection<Alumno> Alumno { get; set; }
        public virtual Ciudad Ciudad1 { get; set; }
        public virtual Universidad Universidad1 { get; set; }
        public virtual ICollection<MateriaFacultad> MateriaFacultad { get; set; }
    }
}
