//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriaAlumno
    {
        public int ID_MateriaAlumno { get; set; }
        public int materia { get; set; }
        public int alumno { get; set; }
    
        public virtual Alumno Alumno1 { get; set; }
        public virtual Materia Materia1 { get; set; }
    }
}
