//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        public Materia()
        {
            this.MateriaAlumno = new HashSet<MateriaAlumno>();
            this.MateriaFacultad = new HashSet<MateriaFacultad>();
        }
    
        public int ID_Materia { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<MateriaAlumno> MateriaAlumno { get; set; }
        public virtual ICollection<MateriaFacultad> MateriaFacultad { get; set; }
    }
}
