//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int ID_Usuario { get; set; }
        public string nombre { get; set; }
        public string contraseña { get; set; }
        public string tipo { get; set; }
    }
}
